In [50]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [51]:
import pandas as pd

In [52]:
df= pd.read_csv("/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv")

In [53]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [54]:
df.shape

(10000, 14)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [58]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [59]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [60]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [61]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [62]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

In [63]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [64]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
X_train, X_test, Y_train, Y_test=train_test_split(x,y, test_size=0.2, random_state=1)

In [67]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((8000, 11), (2000, 11), (8000,), (2000,))

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [70]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [71]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [91]:
model = Sequential()

model.add(Dense(11, activation='sigmoid', input_dim=11))
model.add(Dense(11, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [92]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [101]:
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [113]:
history=model.fit(X_train_scaled, Y_train, epochs=100, validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8677 - loss: 0.3255 - val_accuracy: 0.8531 - val_loss: 0.3429
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3258 - val_accuracy: 0.8525 - val_loss: 0.3437
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8686 - loss: 0.3258 - val_accuracy: 0.8506 - val_loss: 0.3442
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8683 - loss: 0.3254 - val_accuracy: 0.8531 - val_loss: 0.3445
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8684 - loss: 0.3255 - val_accuracy: 0.8519 - val_loss: 0.3429
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8683 - loss: 0.3254 - val_accuracy: 0.8512 - val_loss: 0.3427
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8683 - loss: 0.3249 - val_accuracy: 0.8531 - val_loss: 0.3461
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8681 - loss: 0.3254 - val_accuracy: 0.8525 - val_loss: 0.3429
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8678 - loss: 0.3257 - val_accuracy: 0.8537 - val_loss: 0.3434
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8675 - loss: 0.3254 - val_accuracy: 0.8512 - val_loss: 0.3430
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8692 - loss: 0.3251 - val_accuracy: 0.8519 - val_loss: 0.3462
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8677 - loss: 0.3251 - val_accuracy: 0.8531 - val_loss: 0.3448
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8687 - loss: 0.3246 - val_accuracy: 0.8531 - val_loss: 0.3445
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8683 - loss: 0.3253 - val_accuracy: 0.8519 - val_loss: 0.3439
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8681 - loss: 0.3242 - val_accuracy: 0.8537 - val_loss: 0.3449
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8672 - loss: 0.3251 - val_accuracy: 0.8550 - val_loss: 0.3436
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8692 - loss: 0.3249 - val_accuracy: 0.8506 - val_loss: 0.3458
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8670 - loss: 0.3247 - val_accuracy: 0.8544 - val_loss: 0.3437
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8686 - loss: 0.3247 - val_accuracy: 0.8525 - val_loss: 0.3445
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8703 - loss: 0.3246 - val_accuracy: 0.8519 - val_loss: 0.3452
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8666 - loss: 0.3243 - val_accuracy: 0.8512 - val_loss: 0.3443
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8684 - loss: 0.3247 - val_accuracy: 0.8525 - val_loss: 0.3449
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8698 - loss: 0.3242 - val_accuracy: 0.8519 - val_loss: 0.3450
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8684 - loss: 0.3243 - val_accuracy: 0.8531 - val_loss: 0.3437
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8691 - loss: 0.3244 - val_accuracy: 0.8531 - val_loss: 0.3441
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8673 - loss: 0.3243 - val_accuracy: 0.8519 - val_loss: 0.3442
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8680 - loss: 0.3238 - val_accuracy: 0.8519 - val_loss: 0.3461
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8684 - loss: 0.3256 - val_accuracy: 0.8519 - val_loss: 0.3456
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8697 - loss: 0.3234 - val_accuracy: 0.8519 - val_loss: 0.3456
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8680 - loss: 0.3240 - val_accuracy: 0.8519 - val_loss: 0.3446
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8705 - loss: 0.3233 - val_accuracy: 0.8537 - val_loss: 0.3467
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8670 - loss: 0.3247 - val_accuracy: 0.8525 - val_loss: 0.3448
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8670 - loss: 0.3239 - val_accuracy: 0.8562 - val_loss: 0.3484
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8692 - loss: 0.3236 - val_accuracy: 0.8519 - val_loss: 0.3464
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8687 - loss: 0.3236 - val_accuracy: 0.8556 - val_loss: 0.3447
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8702 - loss: 0.3236 - val_accuracy: 0.8500 - val_loss: 0.3454
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8692 - loss: 0.3235 - val_accuracy: 0.8506 - val_loss: 0.3451
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8689 - loss: 0.3235 - val_accuracy: 0.8544 - val_loss: 0.3447
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8700 - loss: 0.3243 - val_accuracy: 0.8512 - val_loss: 0.3461
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3230 - val_accuracy: 0.8550 - val_loss: 0.3457
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3235 - val_accuracy: 0.8519 - val_loss: 0.3461
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3231 - val_accuracy: 0.8562 - val_loss: 0.3456
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8695 - loss: 0.3230 - val_accuracy: 0.8537 - val_loss: 0.3455
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8689 - loss: 0.3229 - val_accuracy: 0.8537 - val_loss: 0.3468
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8694 - loss: 0.3230 - val_accuracy: 0.8525 - val_loss: 0.3461
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8697 - loss: 0.3233 - val_accuracy: 0.8531 - val_loss: 0.3455
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3229 - val_accuracy: 0.8544 - val_loss: 0.3457
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8694 - loss: 0.3228 - val_accuracy: 0.8519 - val_loss: 0.3476
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - loss: 0.3229 - val_accuracy: 0.8550 - val_loss: 0.3461
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8706 - loss: 0.3228 - val_accuracy: 0.8581 - val_loss: 0.3464
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8692 - loss: 0.3223 - val_accuracy: 0.8550 - val_loss: 0.3454
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8698 - loss: 0.3226 - val_accuracy: 0.8500 - val_loss: 0.3461
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8698 - loss: 0.3226 - val_accuracy: 0.8544 - val_loss: 0.3461
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8698 - loss: 0.3228 - val_accuracy: 0.8537 - val_loss: 0.3459
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8691 - loss: 0.3226 - val_accuracy: 0.8531 - val_loss: 0.3486
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8692 - loss: 0.3231 - val_accuracy: 0.8556 - val_loss: 0.3464
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8695 - loss: 0.3221 - val_accuracy: 0.8556 - val_loss: 0.3467
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8680 - loss: 0.3215 - val_accuracy: 0.8525 - val_loss: 0.3474
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8689 - loss: 0.3222 - val_accuracy: 0.8550 - val_loss: 0.3458
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8697 - loss: 0.3226 - val_accuracy: 0.8569 - val_loss: 0.3448
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8691 - loss: 0.3210 - val_accuracy: 0.8525 - val_loss: 0.3491
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8703 - loss: 0.3221 - val_accuracy: 0.8531 - val_loss: 0.3468
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8698 - loss: 0.3224 - val_accuracy: 0.8525 - val_loss: 0.3466
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8692 - loss: 0.3220 - val_accuracy: 0.8581 - val_loss: 0.3459
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8694 - loss: 0.3223 - val_accuracy: 0.8537 - val_loss: 0.3469
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8692 - loss: 0.3222 - val_accuracy: 0.8525 - val_loss: 0.3472
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8695 - loss: 0.3223 - val_accuracy: 0.8569 - val_loss: 0.3456
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3218 - val_accuracy: 0.8550 - val_loss: 0.3457
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8680 - loss: 0.3219 - val_accuracy: 0.8550 - val_loss: 0.3466
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8694 - loss: 0.3214 - val_accuracy: 0.8556 - val_loss: 0.3463
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8697 - loss: 0.3218 - val_accuracy: 0.8544 - val_loss: 0.3472
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8691 - loss: 0.3216 - val_accuracy: 0.8544 - val_loss: 0.3463
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8684 - loss: 0.3216 - val_accuracy: 0.8537 - val_loss: 0.3457
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8708 - loss: 0.3216 - val_accuracy: 0.8531 - val_loss: 0.3483
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8683 - loss: 0.3214 - val_accuracy: 0.8544 - val_loss: 0.3473
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8686 - loss: 0.3207 - val_accuracy: 0.8544 - val_loss: 0.3499
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8697 - loss: 0.3212 - val_accuracy: 0.8537 - val_loss: 0.3472
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8692 - loss: 0.3214 - val_accuracy: 0.8531 - val_loss: 0.3480
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - loss: 0.3214 - val_accuracy: 0.8525 - val_loss: 0.3485
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8702 - loss: 0.3202 - val_accuracy: 0.8519 - val_loss: 0.3488
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8680 - loss: 0.3207 - val_accuracy: 0.8550 - val_loss: 0.3493
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8695 - loss: 0.3208 - val_accuracy: 0.8550 - val_loss: 0.3468
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8687 - loss: 0.3210 - val_accuracy: 0.8531 - val_loss: 0.3472
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8698 - loss: 0.3206 - val_accuracy: 0.8519 - val_loss: 0.3474
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8691 - loss: 0.3212 - val_accuracy: 0.8550 - val_loss: 0.3498
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8684 - loss: 0.3207 - val_accuracy: 0.8525 - val_loss: 0.3486
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8698 - loss: 0.3207 - val_accuracy: 0.8531 - val_loss: 0.3475
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8686 - loss: 0.3213 - val_accuracy: 0.8556 - val_loss: 0.3464
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8675 - loss: 0.3203 - val_accuracy: 0.8550 - val_loss: 0.3481
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8689 - loss: 0.3203 - val_accuracy: 0.8537 - val_loss: 0.3475
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8692 - loss: 0.3206 - val_accuracy: 0.8537 - val_loss: 0.3471
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8705 - loss: 0.3208 - val_accuracy: 0.8544 - val_loss: 0.3500
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8714 - loss: 0.3210 - val_accuracy: 0.8556 - val_loss: 0.3475
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - loss: 0.3200 - val_accuracy: 0.8550 - val_loss: 0.3472
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8698 - loss: 0.3203 - val_accuracy: 0.8556 - val_loss: 0.3463
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8691 - loss: 0.3201 - val_accuracy: 0.8556 - val_loss: 0.3474
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8691 - loss: 0.3201 - val_accuracy: 0.8562 - val_loss: 0.3490
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8681 - loss: 0.3204 - val_accuracy: 0.8562 - val_loss: 0.3476
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8689 - loss: 0.3197 - val_accuracy: 0.8525 - val_loss: 0.3486
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8711 - loss: 0.3199 - val_accuracy: 0.8531 - val_loss: 0.3485

In [114]:
model.layers[0].get_weights()

[array([[ 0.17459455,  0.22556543, -0.03050503,  0.13968973,  0.06122228,
         -0.4953728 ,  0.06127261,  0.555911  ,  0.07182442, -0.569906  ,
          0.28301603],
        [-1.1257446 ,  0.302559  ,  2.0467417 ,  0.39315182, -0.5045559 ,
          0.5550281 , -0.31030887, -0.50948817, -2.1348364 , -0.32193655,
          0.9232038 ],
        [-0.47502574,  0.89468205, -0.53154415,  0.42139074,  0.5010087 ,
          0.00975378, -0.33199802,  0.32605588, -0.14992994,  0.18847464,
         -0.32064915],
        [ 0.02037732, -0.70449054, -0.11994127,  0.47772586, -1.2127866 ,
         -0.51942587,  0.02060159, -1.5900887 ,  0.2790682 ,  0.39762387,
         -0.50565064],
        [-1.6635385 , -0.35534   ,  0.40036294,  0.8845769 ,  0.83418334,
         -0.80191344,  2.2850277 , -0.85808784,  0.27034536, -0.16647649,
          0.2145037 ],
        [-0.11060984,  0.51730645, -1.0824229 , -0.44444343, -0.34833276,
         -0.19198903, -0.14332597, -0.0447078 , -0.4801273 ,  0.2767952 ,
          0.710206  ],
        [-1.010461  ,  0.13879414,  0.3686544 ,  0.88819516,  0.05242614,
          0.9941184 , -0.3282846 ,  0.1862156 , -0.5656677 ,  0.05401224,
          0.76788163],
        [-0.09969206, -0.6307665 ,  0.20279652, -0.25693703, -0.01827159,
          0.49338314, -0.347042  , -0.23392005,  0.14321452,  1.0738972 ,
          0.03078017],
        [ 0.4090624 , -0.5201281 , -0.34400672, -0.49194887, -0.5869548 ,
         -0.15693179, -0.71052814, -0.7083537 , -0.3218805 , -0.13950607,
          0.35001126],
        [-0.5523224 ,  0.67077225, -0.79535884, -0.4349148 ,  0.22509709,
         -0.15911753, -0.19609062,  0.14895533, -0.21868965,  0.57031757,
          0.18886314],
        [-0.06627018,  1.537825  ,  0.17109625,  0.557853  ,  0.11461866,
          0.23568107,  0.11786378,  0.08391995,  0.01738283,  1.0222093 ,
          0.53003794]], dtype=float32),
 array([ 1.0168468 ,  0.1697635 , -0.64825684,  0.0865804 , -0.4391751 ,
        -0.03586081, -0.18726452,  0.23612571,  0.7816986 , -0.1491783 ,
        -0.7484392 ], dtype=float32)]

In [115]:
model.layers[1].get_weights()

[array([[-0.25277153,  0.40297318,  0.50945663, -0.7833474 , -0.18182237,
         -0.5722737 ,  1.1288656 ,  0.47374332,  0.01890821, -1.1712158 ,
         -0.75593084],
        [ 0.34689173, -0.18867925,  0.41750652,  0.34679234,  0.32838526,
         -0.12198714,  0.38981324, -0.02400967,  0.03942611, -0.70646673,
         -0.58327836],
        [-0.2231862 ,  1.1323334 ,  0.59491515,  0.24794592,  0.32191622,
          0.44352514,  0.28224906, -0.5362052 ,  0.10124521, -0.12728932,
          0.22645569],
        [ 0.75180435, -0.36010447,  0.09948807,  0.2590221 , -0.55342364,
          0.7103255 , -0.27118868,  0.00267938, -0.27155936,  1.0199349 ,
          0.33005822],
        [-0.5554676 ,  0.68598443,  0.06127954, -0.48704454, -0.672428  ,
         -0.17136306,  0.07733566, -0.3755116 ,  0.06037607,  0.833653  ,
          0.6898139 ],
        [ 0.7083612 , -0.60080844, -0.24879667,  0.29511905, -0.5776193 ,
          0.7047104 ,  0.06550312, -0.15147807, -0.12037089, -1.1129994 ,
         -1.2482884 ],
        [-0.24791488, -0.51726335, -0.00184152,  0.3726196 ,  0.52393323,
          0.3512438 , -1.2798513 ,  0.576194  , -0.47597837,  0.8950797 ,
          1.0203171 ],
        [ 0.45583367,  0.43387634, -0.4050743 ,  0.4156956 , -0.00571022,
          0.44269893,  0.42127782,  0.48837152, -0.21321897, -0.3197181 ,
         -0.7644405 ],
        [ 0.08870008, -1.1543876 , -0.77129334,  0.59747475,  0.22313316,
          0.30884153, -0.45305145,  0.70357686, -0.03371793, -0.0125838 ,
         -0.7704869 ],
        [-0.11606385,  0.469916  ,  0.21881145, -0.02190162,  0.02017834,
          0.4971585 ,  0.57895917,  0.56505114, -0.05639833,  0.2809048 ,
          0.724221  ],
        [ 0.35129863, -0.63977194, -0.15109853,  0.04659972,  0.31074566,
         -0.07766664, -0.725673  , -0.4780886 , -0.2466689 , -0.08108661,
         -0.0061433 ]], dtype=float32),
 array([ 0.06758302, -0.00718224, -0.08168347, -0.00235678,  0.07599209,
         0.07081842,  0.09316444,  0.13692543, -0.06788343, -0.19347794,
         0.15674153], dtype=float32)]

In [116]:
model.layers[2].get_weights()

[array([[-0.555864 ],
        [ 2.6706107],
        [ 1.0026708],
        [-1.3225486],
        [ 0.7923534],
        [-0.6144899],
        [ 1.2549459],
        [-1.2289432],
        [-0.2509208],
        [ 1.7869315],
        [ 3.0432198]], dtype=float32),
 array([-0.11656737], dtype=float32)]

In [117]:
y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [118]:
y_pred=np.where(y_log>0.5,1,0)

In [119]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred)

0.864

In [120]:
import matplotlib.pyplot as plt

In [121]:
history.history

{'accuracy': [0.8676562309265137,
  0.8690624833106995,
  0.8685937523841858,
  0.8682812452316284,
  0.8684375286102295,
  0.8682812452316284,
  0.8682812452316284,
  0.8681250214576721,
  0.8678125143051147,
  0.8675000071525574,
  0.8692187666893005,
  0.8676562309265137,
  0.8687499761581421,
  0.8682812452316284,
  0.8681250214576721,
  0.8671875,
  0.8692187666893005,
  0.8670312762260437,
  0.8685937523841858,
  0.870312511920929,
  0.8665624856948853,
  0.8684375286102295,
  0.8698437213897705,
  0.8684375286102295,
  0.8690624833106995,
  0.8673437237739563,
  0.867968738079071,
  0.8684375286102295,
  0.8696874976158142,
  0.867968738079071,
  0.8704687356948853,
  0.8670312762260437,
  0.8670312762260437,
  0.8692187666893005,
  0.8687499761581421,
  0.8701562285423279,
  0.8692187666893005,
  0.8689062595367432,
  0.8700000047683716,
  0.8690624833106995,
  0.8684375286102295,
  0.8690624833106995,
  0.8695312738418579,
  0.8689062595367432,
  0.8693749904632568,
  0.8696874976158142,
  0.8690624833106995,
  0.8693749904632568,
  0.8693749904632568,
  0.8706250190734863,
  0.8692187666893005,
  0.8698437213897705,
  0.8698437213897705,
  0.8698437213897705,
  0.8690624833106995,
  0.8692187666893005,
  0.8695312738418579,
  0.867968738079071,
  0.8689062595367432,
  0.8696874976158142,
  0.8690624833106995,
  0.870312511920929,
  0.8698437213897705,
  0.8692187666893005,
  0.8693749904632568,
  0.8692187666893005,
  0.8695312738418579,
  0.8690624833106995,
  0.867968738079071,
  0.8693749904632568,
  0.8696874976158142,
  0.8690624833106995,
  0.8684375286102295,
  0.8707812428474426,
  0.8682812452316284,
  0.8685937523841858,
  0.8696874976158142,
  0.8692187666893005,
  0.8693749904632568,
  0.8701562285423279,
  0.867968738079071,
  0.8695312738418579,
  0.8687499761581421,
  0.8698437213897705,
  0.8690624833106995,
  0.8684375286102295,
  0.8698437213897705,
  0.8685937523841858,
  0.8675000071525574,
  0.8689062595367432,
  0.8692187666893005,
  0.8704687356948853,
  0.8714062571525574,
  0.8693749904632568,
  0.8698437213897705,
  0.8690624833106995,
  0.8690624833106995,
  0.8681250214576721,
  0.8689062595367432,
  0.87109375],
 'loss': [0.3255231976509094,
  0.32580047845840454,
  0.3257942497730255,
  0.325369268655777,
  0.32549718022346497,
  0.3254248797893524,
  0.324901282787323,
  0.32535406947135925,
  0.3257465064525604,
  0.3254408538341522,
  0.32506468892097473,
  0.325077086687088,
  0.3246486783027649,
  0.3253015875816345,
  0.324223130941391,
  0.3251112699508667,
  0.32494744658470154,
  0.3246820867061615,
  0.32470378279685974,
  0.32455718517303467,
  0.3242689371109009,
  0.32467663288116455,
  0.3242153823375702,
  0.3242928385734558,
  0.3243700861930847,
  0.3243231475353241,
  0.32383179664611816,
  0.32555100321769714,
  0.3233512043952942,
  0.32403677701950073,
  0.32333657145500183,
  0.3246780037879944,
  0.3239154815673828,
  0.3235704302787781,
  0.32362353801727295,
  0.3235599398612976,
  0.32351356744766235,
  0.3234972059726715,
  0.32426831126213074,
  0.32303252816200256,
  0.3235430419445038,
  0.3231179118156433,
  0.3229948878288269,
  0.3229199945926666,
  0.3230307400226593,
  0.3233121931552887,
  0.3229130506515503,
  0.32282406091690063,
  0.32291659712791443,
  0.32280611991882324,
  0.3222883641719818,
  0.3226342797279358,
  0.3226032555103302,
  0.3228009343147278,
  0.32261523604393005,
  0.32312530279159546,
  0.3220788538455963,
  0.32152122259140015,
  0.3222352862358093,
  0.3226040005683899,
  0.321049302816391,
  0.3221217095851898,
  0.3223986327648163,
  0.32196149230003357,
  0.3222915232181549,
  0.3222198188304901,
  0.3222869038581848,
  0.3218367397785187,
  0.32194599509239197,
  0.3214257061481476,
  0.3217781186103821,
  0.32159164547920227,
  0.3216211199760437,
  0.3216332197189331,
  0.3214121162891388,
  0.3207317590713501,
  0.3212210536003113,
  0.32142725586891174,
  0.3214239776134491,
  0.32015812397003174,
  0.3206765055656433,
  0.3208122253417969,
  0.3210277855396271,
  0.3206189274787903,
  0.32123810052871704,
  0.32071608304977417,
  0.3206714391708374,
  0.32126423716545105,
  0.32025060057640076,
  0.32026198506355286,
  0.3206402063369751,
  0.32080748677253723,
  0.321003794670105,
  0.31995460391044617,
  0.3203381597995758,
  0.3201156556606293,
  0.3200656473636627,
  0.32036593556404114,
  0.31966760754585266,
  0.3199194669723511],
 'val_accuracy': [0.8531249761581421,
  0.8525000214576721,
  0.8506249785423279,
  0.8531249761581421,
  0.8518750071525574,
  0.8512499928474426,
  0.8531249761581421,
  0.8525000214576721,
  0.8537499904632568,
  0.8512499928474426,
  0.8518750071525574,
  0.8531249761581421,
  0.8531249761581421,
  0.8518750071525574,
  0.8537499904632568,
  0.8550000190734863,
  0.8506249785423279,
  0.8543750047683716,
  0.8525000214576721,
  0.8518750071525574,
  0.8512499928474426,
  0.8525000214576721,
  0.8518750071525574,
  0.8531249761581421,
  0.8531249761581421,
  0.8518750071525574,
  0.8518750071525574,
  0.8518750071525574,
  0.8518750071525574,
  0.8518750071525574,
  0.8537499904632568,
  0.8525000214576721,
  0.856249988079071,
  0.8518750071525574,
  0.8556249737739563,
  0.8500000238418579,
  0.8506249785423279,
  0.8543750047683716,
  0.8512499928474426,
  0.8550000190734863,
  0.8518750071525574,
  0.856249988079071,
  0.8537499904632568,
  0.8537499904632568,
  0.8525000214576721,
  0.8531249761581421,
  0.8543750047683716,
  0.8518750071525574,
  0.8550000190734863,
  0.8581249713897705,
  0.8550000190734863,
  0.8500000238418579,
  0.8543750047683716,
  0.8537499904632568,
  0.8531249761581421,
  0.8556249737739563,
  0.8556249737739563,
  0.8525000214576721,
  0.8550000190734863,
  0.8568750023841858,
  0.8525000214576721,
  0.8531249761581421,
  0.8525000214576721,
  0.8581249713897705,
  0.8537499904632568,
  0.8525000214576721,
  0.8568750023841858,
  0.8550000190734863,
  0.8550000190734863,
  0.8556249737739563,
  0.8543750047683716,
  0.8543750047683716,
  0.8537499904632568,
  0.8531249761581421,
  0.8543750047683716,
  0.8543750047683716,
  0.8537499904632568,
  0.8531249761581421,
  0.8525000214576721,
  0.8518750071525574,
  0.8550000190734863,
  0.8550000190734863,
  0.8531249761581421,
  0.8518750071525574,
  0.8550000190734863,
  0.8525000214576721,
  0.8531249761581421,
  0.8556249737739563,
  0.8550000190734863,
  0.8537499904632568,
  0.8537499904632568,
  0.8543750047683716,
  0.8556249737739563,
  0.8550000190734863,
  0.8556249737739563,
  0.8556249737739563,
  0.856249988079071,
  0.856249988079071,
  0.8525000214576721,
  0.8531249761581421],
 'val_loss': [0.3428725302219391,
  0.34366264939308167,
  0.3441798686981201,
  0.3445296585559845,
  0.34285518527030945,
  0.3427283465862274,
  0.34605392813682556,
  0.34290799498558044,
  0.3434407413005829,
  0.34298187494277954,
  0.34616053104400635,
  0.34482407569885254,
  0.34449467062950134,
  0.34385186433792114,
  0.34493499994277954,
  0.3435695171356201,
  0.34579184651374817,
  0.3436950445175171,
  0.34450528025627136,
  0.3452213406562805,
  0.3443410098552704,
  0.34494465589523315,
  0.34496209025382996,
  0.3437352776527405,
  0.3441263437271118,
  0.3442487418651581,
  0.34613993763923645,
  0.3455524742603302,
  0.3456346392631531,
  0.3445625603199005,
  0.3467336595058441,
  0.3447752296924591,
  0.34836268424987793,
  0.3464168608188629,
  0.3447100818157196,
  0.3453754186630249,
  0.34508273005485535,
  0.34469613432884216,
  0.34605053067207336,
  0.3456672728061676,
  0.3460633456707001,
  0.34560519456863403,
  0.34548309445381165,
  0.34682196378707886,
  0.3461109399795532,
  0.3454923629760742,
  0.3456588089466095,
  0.3475830852985382,
  0.3460865914821625,
  0.34635698795318604,
  0.3454310894012451,
  0.3460614085197449,
  0.34614503383636475,
  0.34588682651519775,
  0.34864890575408936,
  0.3463938236236572,
  0.34665897488594055,
  0.34736114740371704,
  0.34575504064559937,
  0.34475311636924744,
  0.3491095304489136,
  0.3467918038368225,
  0.3465507924556732,
  0.3458505868911743,
  0.3468780517578125,
  0.34720829129219055,
  0.34556224942207336,
  0.3457498252391815,
  0.3466058373451233,
  0.3463056981563568,
  0.3471774756908417,
  0.34626102447509766,
  0.34567776322364807,
  0.34834975004196167,
  0.34729278087615967,
  0.349893182516098,
  0.34722378849983215,
  0.347990483045578,
  0.3485167622566223,
  0.34884127974510193,
  0.34932807087898254,
  0.34683218598365784,
  0.3472355604171753,
  0.34744617342948914,
  0.3498053252696991,
  0.34863513708114624,
  0.34746676683425903,
  0.34636610746383667,
  0.3480609655380249,
  0.3475252091884613,
  0.34714239835739136,
  0.35002678632736206,
  0.3474569022655487,
  0.3471779227256775,
  0.34633639454841614,
  0.3473852276802063,
  0.3489762246608734,
  0.34764593839645386,
  0.3485642969608307,
  0.3484618365764618]}